//@version=5
strategy("RSI Strategy", overlay=true)

length = input(15)
overSold = input(21)
overBought = input(64)
price = close
vrsi = ta.rsi(price, length)
co = ta.crossover(vrsi, overSold)
cu = ta.crossunder(vrsi, overBought)

// Initialize variables to store the previous trade's side and price
var prev_price = price

if (not na(vrsi))
    // Check if the previous trade was a short at a lower price
    //if (ta.valuewhen(cu, price, 1) > price)
        // Enter long position and trigger alert
    if (co)
        strategy.entry("RsiLE", strategy.long, comment="Buy "+str.tostring(price))
        alert("Long position entered!", alert.freq_once_per_bar)
        prev_price := price

    // Check if the previous trade was a long at a higher price
    //if (ta.valuewhen(co, price, 1) < price)
        // Enter short position and trigger alert
    if (cu)
        strategy.entry("RsiSE", strategy.short, comment="Sell "+str.tostring(price))
        alert("Short position entered!", alert.freq_once_per_bar)
        prev_price := price

